title: hudong の Blog
description: hudong  の Blog

url: https://hudongyida.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: 文章
   url: /articles-zh
 - title: 类别
   url: /categories
 - title: 关于
   url: /about
 - title: 捐赠
   url: /donate

social:
   github: hudongyida
   # linkedin: in/yanan-zhao-7691317b?trk=hp-identity-photo
   # facebook: profile.php?id=100014334455077
   # email: arthurchiao@hotmail.com

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

# google_analytics: "G-5SFP2TKSL7"

# development configurations
host: 0.0.0.0
